export const infoPopups = [
  {
    id: 1,
    name: 'profile',
    typeName: 'profile',
    form: 'formProfile',
    inputOne: 'name',
    placeholderOne: 'Имя',
    inputTwo: 'job',
    placeholderTwo: 'Профессия',
    title: 'Редактировать форму',
  },
  {
    id: 2,
    name: 'card',
    typeName: 'card',
    form: 'formCard',
    inputOne: 'place',
    placeholderOne: 'Название',
    inputTwo: 'card',
    placeholderTwo: 'Ссылка на картинку',
    title: 'Новое место',
  },
  {
    id: 3,
    name: 'avatar',
    typeName: 'avatar',
    form: 'formAvatar',
    inputTwo: 'avatar',
    placeholderTwo: 'Ссылка на картинку',
    title: 'Обновить аватар',
  },
  {
    id: 4,
    name: 'trash',
    typeName: 'trash',
    form: 'formTrash',
    inputTwo: 'trash',
    title: 'Вы уверены?',
  },
];
